//-----------------------------------------------------------------------------
//           Name: stl_list.cpp
//         Author: Kevin Harris
//  Last Modified: 09/25/04
//    Description: This sample demonstrates how to use STL's list container 
//                 to store a series of int values.
//-----------------------------------------------------------------------------

#include <iostream>
#include <list>

using namespace std;

//
// First, let us create a new type, which represents a list container of ints.
// This step is not really necessary, but it helps to keep our code from 
// becoming too cluttered.
//

typedef list< int > myListType;

void printContents( myListType list );

void main( void )
{
    //
    // Create the initial list and load it with some int values to work with.
    // Once that's done, print out the contents for inspection.
    //

    myListType myList;

    myList.push_back( 1 );
    myList.push_back( 2 );
    myList.push_back( 3 );
    myList.push_back( 4 );

    printContents( myList );

    //
    // Now, let's modify the first and last elements of the list using 
    // references generated by calls to front() and back().
    //

    myListType::reference ref_front = myList.front();
    myListType::reference ref_back  = myList.back();

    ref_front = 100; // Change the first element from 1 to 100
    ref_back  = 400; // Change the last element from 4 to 400

    printContents( myList );

    //
    // Ok, let's change them back but this time we'll use iterators instead 
    // reference pointers.
    //
    // Note how we dereference the iterators with * when setting them.
    //

    myListType::iterator it_begin = myList.begin();
    myListType::iterator it_end   = myList.end();

    *it_begin = 1; // Change the first element from 100 to back to 1

    --it_end;
    *it_end   = 4; // Change the last element from 400 to back to 4

    //
    // Whoa...hang on! What's that decrement for?
    //
    // The line above that says "--it_end;" is important because it_end points 
    // to a position which is one past the last element.
    //
    // And since it doesn't point at the last element of myList, we have to 
    // move it back one position by decrementing it. This will make it actually 
    // point to the last element like we want.
    //

    printContents( myList );

    //
    // Now, since a list is a variable-length array we can add elements by 
    // pushing them on to the array's back like so:
    //

    myList.push_back( 25 );
    myList.push_back( 75 );

    printContents( myList );

    //
    // And if you can push elements on, you can also pop them back off like so:
    //

    myList.pop_back();
    myList.pop_back();

    printContents( myList );

    //
    // Of course, if we keep popping the queue, we'll end up with nothing...
    //

    myList.pop_back();
    myList.pop_back();

    printContents( myList );

    myList.pop_back();
    myList.pop_back();

    printContents( myList );
}

void printContents( myListType _list )
{
    //
    // Using iterators, which point to the beginning and ending of the vector,  
    // we can loop through the vector and print out its contents.
    //

    myListType::iterator it_begin = _list.begin();
    myListType::iterator it_end   = _list.end();

    cout << "Contents of myList: ";

    for( /*empty*/; it_begin != it_end; ++it_begin )
    {
        cout << *it_begin << " " ;
    }

    cout << endl;
}
